language: nix
nix: 2.0.4

before_deploy:
  - ls result
  - cp -r result/docs ./docs
  - cp result/index.html ./index.html
  - rm -r result

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
